lab_name: Draelos Lab
lab_short_name: Draelos Lab

collections:
  projects:
  persons:
  news:
    output: true
  bluesky:
    output: false

scholar:
  style: apa
  csl:  _bibliography/apa.csl
  bibliography: recent_references.bib
  sort_by: year,month,day,authors
  order: descending
